UserParameter=swanctl.workers[*],/etc/zabbix/scripts/swanctl.sh workers
UserParameter=swanctl.queues[*],/etc/zabbix/scripts/swanctl.sh queues
UserParameter=swanctl.ikesas[*],/etc/zabbix/scripts/swanctl.sh ikesas
UserParameter=swanctl.scheduled[*],/etc/zabbix/scripts/swanctl.sh scheduled
UserParameter=swanctl.childsas[*],/etc/zabbix/scripts/swanctl-list-sas.sh childsas